### ISSUE TITLE
The button covers the code on mobile

### ISSUE THREAD

**Issue by NomarCub** [jdbrice/obsidian-code-block-copy#11]
This is what it looks for me on Android.

![image](https://user-images.githubusercontent.com/5298006/125746539-054d78be-da73-4ad2-bdbd-464b336293ca.png)

And how it looks on desktop, with the button not in the way.

![image](https://user-images.githubusercontent.com/5298006/125746653-d96bdfdb-9b7c-49da-b5b1-29709c5d82ce.png)

**Comment by jtr109** [comment]
Hello, @NomarCub. I have the same problem as you. I use a temporary CSS snippet to solve it, hope it helps.

```css
.has-copy-button .copy-code-button {
  width: auto;
  margin-top: 0;
}
```

By the way, don't forget to enable it in settings.
